<a href="https://colab.research.google.com/github/NathanaelLUCETTE/projet_ML/blob/main/pokemon_clustering_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test importation du dataset

In [ ]:
import os
import shutil

# Créer le dossier .kaggle s'il n'existe pas
os.makedirs('/root/.kaggle', exist_ok=True)

# Déplacer kaggle.json dans le dossier
shutil.move('/content/kaggle.json', '/root/.kaggle/kaggle.json')

# Donner les bonnes permissions
os.chmod('/root/.kaggle/kaggle.json', 600)

In [ ]:
#installation librairie kaggle
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.18)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [ ]:
#Téléchargement du dataset - ici avec pokemon_dataset_2025
!kaggle datasets download -d darkmatternet/ultimate-pokmon-dataset-2025
!unzip ultimate-pokmon-dataset-2025.zip

#Chargement du dataset dans pandas
import pandas as pd

df = pd.read_csv("pokemon_complete_2025.csv")   # adapte le nom si nécessaire
df.head()

Dataset URL: https://www.kaggle.com/datasets/darkmatternet/ultimate-pokmon-dataset-2025
License(s): CC0-1.0
ultimate-pokmon-dataset-2025.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  ultimate-pokmon-dataset-2025.zip
replace pokemon_complete_2025.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: pokemon_complete_2025.csv

,pokedex_id,name,genus,generation,type_1,type_2,num_types,hp,attack,defense,...,sprite_url,is_dual_type,bmi,attack_defense_ratio,physical_total,special_total,offensive_total,defensive_total,gender_distribution,stat_tier
0,1,bulbasaur,Seed Pokémon,I,grass,poison,2,45,49,49,...,https://raw.githubusercontent.com/PokeAPI/spri...,True,14.1,1.00,98,130,159,159,88% Male / 12% Female,Below Average (300-399)
1,2,ivysaur,Seed Pokémon,I,grass,poison,2,60,62,63,...,https://raw.githubusercontent.com/PokeAPI/spri...,True,13.0,0.98,125,160,202,203,88% Male / 12% Female,Average (400-499)
2,3,venusaur,Seed Pokémon,I,grass,poison,2,80,82,83,...,https://raw.githubusercontent.com/PokeAPI/spri...,True,25.0,0.99,165,200,262,263,88% Male / 12% Female,Strong (500-599)
3,4,charmander,Lizard Pokémon,I,fire,NaN,1,39,52,43,...,https://raw.githubusercontent.com/PokeAPI/spri...,False,23.6,1.21,95,110,177,132,88% Male / 12% Female,Below Average (300-399)
4,5,charmeleon,Flame Pokémon,I,fire,NaN,1,58,64,58,...,https://raw.githubusercontent.com/PokeAPI/spri...,False,15.7,1.10,122,145,224,181,88% Male / 12% Female,Average (400-499)

In [ ]:
cols_to_drop = [
    "num_types", "base_experience", "ability_1", "ability_2", "genus",
    "hidden_ability", "habitat", "growth_rate", "egg_groups", "gender_rate",
    "is_mythical", "sprite_url", "description", "gender_distribution", "bmi", "base_happiness"
]

df.drop(columns=cols_to_drop)

,pokedex_id,name,generation,type_1,type_2,hp,attack,defense,sp_attack,sp_defense,...,capture_rate,base_happiness,hatch_counter,is_dual_type,attack_defense_ratio,physical_total,special_total,offensive_total,defensive_total,stat_tier
0,1,bulbasaur,I,grass,poison,45,49,49,65,65,...,45,70,20,True,1.00,98,130,159,159,Below Average (300-399)
1,2,ivysaur,I,grass,poison,60,62,63,80,80,...,45,70,20,True,0.98,125,160,202,203,Average (400-499)
2,3,venusaur,I,grass,poison,80,82,83,100,100,...,45,70,20,True,0.99,165,200,262,263,Strong (500-599)
3,4,charmander,I,fire,NaN,39,52,43,60,50,...,45,70,20,False,1.21,95,110,177,132,Below Average (300-399)
4,5,charmeleon,I,fire,NaN,58,64,58,80,65,...,45,70,20,False,1.10,122,145,224,181,Average (400-499)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,raging-bolt,IX,electric,dragon,125,73,91,137,89,...,10,0,50,True,0.80,164,226,285,305,Strong (500-599)
1021,1022,iron-boulder,IX,rock,psychic,90,120,80,68,108,...,10,0,50,True,1.50,200,176,312,278,Strong (500-599)
1022,1023,iron-crown,IX,steel,psychic,90,72,100,122,108,...,10,0,50,True,0.72,172,230,292,298,Strong (500-599)
1023,1024,terapagos,IX,normal,NaN,90,65,85,65,85,...,255,50,5,False,0.76,150,150,190,260,Average (400-499)
1024,1025,pecharunt,IX,poison,ghost,88,88,160,88,88,...,3,0,20,True,0.55,248,176,264,336,Legendary/Pseudo (600+)